* Поступление
** DONE Подать документы
   CLOSED: [2017-10-05 Чт 10:09]
-[] Заявление
-[] Копия паспорта
** DONE Интервью
   CLOSED: [2017-10-05 Чт 10:00]
** DONE Договор
   CLOSED: [2017-10-05 Чт 10:00]
* 1 семестр
** Иностранный язык
*** Дворцова Анна Викторовна
[[file:/][]]
mailto:xxxxx@mail.ru
tel:+79200000000
*** Тема 1 Современныя высокотехнологичная компания: типы организационных структур, их основные характеристики, стратегии бизнеса
**** Task 6 Past Simple
     file:'./1 семестр/'
     DEADLINE: <2017-09-30 Сб>
**** Task 7 Reading & Writing
     DEADLINE: <2017-10-06 Пт>
**** Task 8 Final Assignment
     DEADLINE: <2017-10-20 Пт>
**** Task 9 Company Progile
     DEADLINE: <2017-10-22 Вс>
**** Task 10 Self-Introduction
     DEADLINE: <2017-10-22 Вс>
*** Тема 2 Корпоративная культура
**** Task 11 National Culture
     DEADLINE: <2017-10-25 Ср>
**** Task 12 Engagement
     DEADLINE: <2017-10-28 Сб>
**** Task 13 Articles, nouns, pronouns
     DEADLINE: <2017-10-31 Вт>
**** Task 14 Articles
     DEADLINE: <2017-11-04 Сб>
**** Task 15 What is Corparate Culture
     DEADLINE: <2017-11-10 Пт>
     :LOGBOOK:
     CLOCK: [2017-10-31 Вт 22:03]--[2017-10-31 Вт 22:07] =>  0:04
     :END:
**** Task 16 Final Assignment
*** Тема 3 Лидерство и управление: характеристики и типы
*** Тема 4 Формирование команды, работа в команде
** Инструменты планомерного создания инноваций на предприятии, ТРИЗ
*** Задание до приезда
**** Задание 1 Предварительное чтение
*** Тема 1 Общая характеристика методических средств поддержки инновационной деятельности и развития креативности
**** Лекция 1 Общая характеристика методических средств поддержки инновационной деятельности и развития креативности
*** Тема 2 ТРИЗ Структура инструментов и средств поддержки при поиске новых решений
**** Лекция 2 ТРИЗ. Структура инструментов и средств поддержки при поиске новых решений
**** Задание 2 Объект исследования
     DEADLINE: <2017-10-12 Чт>
*** Тема 3 ТРИЗ - инструмены выявления и углубленного анализа задач
**** Лекция 3 ТРИЗ - инструменты выявления и углубленного анализа задач
**** Задание 3 Утверждение темы "Проектной работы"
     DEADLINE: <2017-11-12 Вс>
*** Тема 4 Понятие инструмента решения задач в ТРИЗ. Различные модели представления задач
*** Тема 5 Информационные и психологические средства поддержки при решении изобретательских задач
*** Тема 6 Закономерности развития технических систем и развития креативности
** История, философия и методология естествознания
*** Задание до приезда Философские проблемы и парадигмы современного естествознания и техники
**** Задание 1 Вопросы к тексту о рационализме и эмпиризме
     DEADLINE: <2017-10-07 Сб>
**** Текст о рационализме и эмпиризме
**** Задание 2 Вопросы к тексту о позитивизме
     DEADLINE: <2017-10-07 Сб>
**** Текст о позитивизме XIX-начала XX века
**** Задание 3 Вопросы по прочитанному материалу
     DEADLINE: <2017-10-08 Вс>
*** Тема 1 История науки
**** Лекция 1 История философии и науки с античности до Нового времени
*** Тема 2 Философия о научном познании. Основные концепции
**** Лекция 3 Проблема роста научного знания у Поппера. Эволюционная эпистемология Поппера и Тулмана
**** Лекция 4 Пол Фейерабенд и Имре Лакатос
**** Задание 6 Вопросы к тексту о постпозитивизме
     DEADLINE: <2017-10-19 Чт>
**** Текст о постпозитивизме
*** Тема 3 Актуальные проблемы современной философской науки
**** Лекция 6 Современные споры между реализмом и антиреализмом
**** Лекция 7 Три методологические революции в физике. Объектная модель науки
**** Лекция 8 Структура естественнонаучного знания
**** Лекция 10 Социальная лаборатория
**** Задание 4 Вопросы к лекциям
     DEADLINE: <2017-10-19 Чт>
**** Задание 5 Вопросы к тексту о логическом позитивизме
     DEADLINE: <2018-01-07 Вс>
**** Текст о логическом позитивизме
**** Задание 7 Вопросы по лекциям 6 и 10. Подготовка к Вебинару
     DEADLINE: <2017-11-08 Ср>
**** Вебинар
     DEADLINE: <2017-11-11 Сб>
*** Литература
*** Дополнительные материалы
** Маркетинг и стратегия наукоемких технологий
*** Кузюк Максим Вадимович
Руководитель головного предприятия заказчика
Руководил Калашниковым, Автовазом, Технодинамикой, в н.в. РТИ
Работал в консалтинговой компани BCG
Основатель кафедры
Молод, богат, уверен в себе, жена и 3 детей от старшего школьного до детсадовского возраста.
*** Задание до приезда
**** Задание 1 Основы маркетинга
***** Прочитать главы 1, 2, 3, 4 книги Филипа Котлера "Основы маркетинга"
***** Сформулировать 2 вопроса по книге из своей профессиональной деятельности
      DEADLINE: <2017-10-08 Вс>
**** Задание 2 Основы маркетинга
***** Прочитать главы 6, 8, 9, 12 книги Филипа Котлера "Основы маркетинга"
***** Сформулировать 2 вопроса из вашей профессиональной деятельности, ответы на которые есть в книге. Дать свое пояснение с кратким описание
      DEADLINE: <2017-11-30 Чт>
*** Тема 1 Ключевые элементы и инструменыт маркетинга и стратегии
**** DONE Лекция 1 Ключевые элементы и инструменты маркетинга и стратегии 
     CLOSED: [2017-10-27 Пт 22:10]
**** DONE Лекция 2 Размер рынка, сегментация и требования потребителя
     CLOSED: [2017-10-27 Пт 22:10]
**** DONE Лекция 3 Маркетинг запуска новых продуктов
     CLOSED: [2017-10-27 Пт 22:10]
*** Тема 2 Практические интрументы маркетинга
**** Лекция 4 Брендирование технологической компании
*** Тема 3 Разработка стратегии в сфере технологий
**** Лекция 5 Стратегия в технологиях - ключевые элементы и инструменты
*** Литература
** Системный инженеринг
*** Бородкин Александр Александрович
*** Задание до приезад
**** Задание 1 Предварительное чтение
**** Системный инжиниринг для усовершенствования технических решений
*** Тема 1 Введение в системный инжиниринг
**** Лекция 1 Основные понятия и определения. Предмет и метод системного инжиниринга
*** Тема 2 Определене, предмет и метод системного инжиниринга
**** Лекция 2 Ключевые особенности системного инжиниринга
*** Тема 3 Практические аспекты системного инжиниринга
**** Вопросы по текущему контролю
**** Лекция 3 Стахостические системы
**** Лекция 4 Практические аспеткы системного инжиниринга, примеры функционального мышления
**** Задание 2 Отработка методологии системного инжиниринга при поиске технических решений
     DEADLINE: <2018-01-06 Сб>
*** Литература
*** Дополнительные материалы
** Экономика, организация и управление технологическими инновациями
*** Паламарчук Виктор Петрович
*** Задание до приезда
*** Тема 1 Анализ финансового состояния технологической компании
*** Тема 2 Управленческий учет и принятие решений
*** Тема 3 Корпоративная финансовоя политика
*** Тема 4 Оценка эффективности технологической компании
*** Тема 5 Создание ценности
*** Тема 6 Интеграция стратегии и финансов
*** Литература
*** Дополнительные материалы
** Эмоциональный интеллект
*** Стюарт Хеллер
Нью-Йоркский занудный старик
*** Задание до приезда
*** Тема 1 Связность
    DEADLINE: <2017-11-05 Вс>
*** Тема 2 Отношения
*** Тема 3 Податливость
*** Тема 4 Возбудимость
*** Тема 5 Внимание
*** Тема 6 Сопротивление
*** Литература
** Управление временем
** Разработка инженерных систем
*** Романов Алексей Александрович
*** Тема 1 Основные понятия
**** Лекция 1 Введение
**** Лекция 2 Жизненный цикл
*** Тема 2 Анализ системы
*** Тема 3 Синтез нового продукта
*** Тема 4 Организация процессов
*** Литература
** Дополнительные задания
*** Классный час
*** Сколково
    CLOCK: [2017-11-02 Чт 11:31]--[2017-11-02 Чт 11:31] =>  0:00
*** Боинг
*** Розыгрыш
    DEADLINE: <2017-10-20 Пт>
**** Придумать идею
**** Реализовать
**** Производство видео
**** Защита
*** Сувенир
    DEADLINE: <2017-10-19 Чт>
**** Обсуждение идей
**** Детализаци разработки
**** Производство
**** Подготовка презентации
**** Защита
*** Видео IDEO
    DEADLINE: <2017-10-08 Вс>
** Внеучебная деятельность
*** Проживание
**** TODO Вселиться в общежитие
**** TODO Оплатить проживание
** Административное
*** Сдать диплом на хранение
*** Получить студенческий билет
** Практика
* 2 семестр
** Введение в операции
** Индустриализация
** Иностранный язык
** История, философия и методология естествознания
*** Тема 4
**** Лекция 11 Социология науки. Место науки в современной цивилизации
**** Лекция 12 Философия пространства и времени
**** Лекция 13 Философия квантовой механики
** Маркетинг и стратегия наукоемких технологий
** Основы управления проектами
** Теория и методы принятия решений
** Управление качеством
** Управление многофункциональными командами, группами и предприятиями
** Фундаментальные основы наукоемких технологий
** Практика
** Корея
* 3 семестр
** Организация производства и систем снабжения
** Инструменты руководителя проекта
** Национальная инновационная система
** Экономика и право интеллектуальной собственности
** Практика
** Государственный квалификационный экзамен
* 4 семестр
** Практика
* ВКР
** ВКР
*** Встреча с научным руководителем
*** Определение направления работы
    DEADLINE: <2017-12-17 Вс>
** Курсовая работа 1
*** Предаставление в СДО темы КР1
*** Утверждение темы КР1
    Протокол заседания кафедры
*** Выполнение КР1
*** Предоставление КР1 в СДО антиплагиат
    Ведомость по уникальности к КР1
*** Защита КР1
*** Предоставление в СДО КР1 и Чек-листа к КР1 в формате PDF с подписью и оценкой научного руководителя
     Скан КР1, скан чек-листа к КР1
*** Предоставление КР1 и Чек-листа к КР1 с подписью и оценкой научного руководителя в бумажной форме на кафедру
     КР1, Чек-лист к КР1
** Учебная практика
*** Учебная практика
    Скан Отчета по учебной практике
*** Предоставление Отчета по Учебной практике с подписью и оценкой руководителя в бумажном виде на кафедру
     Отчет по учебной практике
** Курсовая работа 2
*** Предоставление темы КР2
*** Утверждение темы КР2
    Протокол заседания кафедры
*** Выполнение КР2
*** Предоставление КР2 в СДО для проверки антиплагиат
    Ведомость по уникальности КР2
*** Защита КР2
*** Предоставление в СДО КР2 и Чек-листа к КР2 в формате PDF с подписью и оценкой научного руководителя
    Скан КР2, Скан Чек-листа к КР2
*** Предоставление КР2 и Чек-листа к КР2 с подписью и оценкой научного руководителя в бумажном виде на кафедру
    КР2, Чек-лист к КР2
** Статья
*** Тезисы статьи по тематике ВКР
*** Подготовка статьи в соавторстве с научным руководителем
*** Оформление статьи в соответствии с требованиями научного журнала
*** Опубликование научной статьи и предоставление в электронном виде в СДО
    Скан опубликованной статьи
*** Предоставление научной статьи на бумажном носителе на кафедру
    Статья на бумажном носителе
** НИР
*** НИР
    Скан отчета по НИР
*** Предоставление отчета по НИР2 с подписью и оценкой руководителя в бумажном виде на кафедру
    Отчет по НИР
** ВКР
*** Предоставление тем ВКР с СДО
    Протокол заседания кафедры
*** Предоставление цели и задач ВКР в СДО
*** Утверждение тем ВКР
    Скан заявления на утверждение темы ВКР
    Заявление на утверждение темы ВКР (Приказ МФТИ на утверждение темы ВКР)
** Преддипломная практика
*** Преддипломная практика
    Скан Отчета по преддипломной практике
*** Предоставление Отчета по преддипломной практике с подписью и оценкой научного руководителя в бумажном виде на кафедру
    Отчет по преддипломной практике
** ВКР 
*** Согласование у научного руководителя полного текста и оформления работы
    Обратная связь от научного руководителя
*** Устранение замечаний научного руководителя
    Обратная связь от научного руководителя
*** Предоставление текста ВКР в СДО для проверки антиплагиат
    Ведомость по уникальности ВКР
*** Предоставление научному руководителю материалов выступления студента по предзащите ВКР (презентация, видео)
*** Устанение замечаний научного руководителя
    Обратная связь от научного руководителя
*** Загрузка в СДО материалов по предзащите ВКР (видео, презентация, отзыв научного руководителя по предзащите)
    Рекомендация по результатам предзащиты
*** Предоставление Чек-листа к ВКР в формате PDF с подписью и оценкой научного руководителя
    Скан Чек-листа к ВКР
*** Загрузка в СДО скана Акта экспертизы об отсутствии тайны и возможности опубликования ВКР в откртых источниках
    Скан Акта экспертизы об отсутствии тайны и возможности опубликования ВКР
*** Предоставление на кафедру полностью оформленной ВКР (в типографском переплете) с подписью научного руководителя и студента
    Рукопись ВКР
*** Предоставление на кафедру отзыва на ВКР от научного руководителя
    Отзыв от научного руководителя
*** Предоставление на кафедру отзыва на ВКР от рецензента
    Отзыв от рецензента
*** Предоставление на кафедру Акта экспертизы об отсутствии тайны и возможности опубликования ВКР
    Акт экспертизы об отсутствии тайны об отсутвии тайны и возможности опубликования ВКР
*** Предоставление на кафедру Чек-листа к ВКР с подписью и оценкой научного руководителя
    Чек-лист к ВКР
*** Предоставление в СДО полностью оформленной ВКР с подписями научного руководителя и студента в формате PDF
    Скан рукописи ВКР


